<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePatientsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        /*Schema::create('patients',function (Blueprint $table) {
            $table->string('name',10); 
			$table->string('user_ID',12)->unique();
			 $table->string('password',10);
			 $table->string('height',5);
			 $table->string('weight',5);
			 $table->string('gender',5);
			 $table->string('blood_type',5);
			 $table->string('education_level',10);
		        $table->string('occupation',10);
				$table->string('marital_status',6);
				$table->string('native',6);
				$table->string('Drinking_Habits',15);
				$table->string('Drinking_Habits_Year',10)->nullable();
				$table->string('Drinking_Year',10)->nullable();
				$table->string('Drinking_CC',10);
				$table->string('Alcohol_Concentration',50);
				$table->string('Smoking_More',50);
				$table->string('Smoking_Year',50)->nullable();
		        	$table->string('Smoking',50)->nullable();
					$table->string('Quit_Smoking',50)->nullable();
					$table->string('Withdraw_the_Time_to_Quit_Smoking',50)->nullable();
					$table->string('Smoking_Average',50)->nullable();
		        	$table->string('Smoking_Lungs',50)->nullable();
					$table->string('Areca_More',50);
					$table->string('Areca_Year',50)->nullable();
					$table->string('Areca_Now',50)->nullable();
					$table->string('Quit_Areca',50)->nullable();
		        	$table->string('Withdraw_the_Time_to_Quit_Areca',50)->nullable();
		        	$table->string('Areca_Time',50)->nullable();
					$table->string('Areca_Num',50)->nullable();
					$table->string('Tea_More',50);
					$table->string('Tea_Year',50)->nullable();
		        	$table->string('Tea_Now',50)->nullable();
					$table->string('Quit_Tea',50)->nullable();
					$table->string('Withdraw_the_Time_to_Quit_Tea',50)->nullable();
					$table->string('Tea_Num',50)->nullable();
					$table->string('Tea_Time',50)->nullable();
					$table->string('Coffee_More',50);
		        $table->string('Coffee_Year',50)->nullable();
				$table->string('Coffee_Now',50)->nullable();
				$table->string('Quit_Coffee',50)->nullable();
				$table->string('Withdraw_the_Time_to_Quit_Coffee',50)->nullable();
				$table->string('Coffee_Creamer',50)->nullable();
		        $table->string('Coffee_Num',50)->nullable();
				$table->string('Coffee_Time',50)->nullable();
				$table->string('Acid_Food',50);
				$table->string('Spicy_Food',50);
				$table->string('Sweet_Food',50);
				$table->string('Fried_Food',50);
				$table->string('Pickled_Food',50);
				$table->string('Sleep_Time',50);
		        $table->string('Insomnia',50);
				$table->string('NG_Feel',50);
				$table->string('Nervous',50);
				$table->string('Fall',50);
				$table->string('Angry',50);
				$table->string('Upset',50);
				$table->string('Gastritis',50);
				$table->string('Gastritis_Year',50)->nullable();
		        $table->string('Gastric_Ulcer',50);
				$table->string('Gastric_Ulcer_Year',50)->nullable();
				$table->string('Duodenal_Ulcer',50);
				$table->string('Duodenal_Ulcer_Year',50)->nullable();
		        $table->string('Inflammatory_Bowel_Disease',50);
				$table->string('Inflammatory_Bowel_Disease_Year',50)->nullable();
				$table->string('Proof',50);
				$table->string('Proof_Disease',50)->nullable();
		        $table->string('Proof_Disease_Year',50)->nullable();
				$table->string('Diabetes',50);
				$table->string('Diabetes_Year',50)->nullable();
				$table->string('High_Blood_Lipids',50);
				$table->string('High_Blood_Lipids_Year',50)->nullable();
		        $table->string('Fat',50);
				$table->string('Fat_Year',50)->nullable();
				$table->string('Liver_Disease',50);
				$table->string('Liver_Disease_Year',50)->nullable();
				$table->string('Cirrhosis_Liver',50);
				$table->string('Cirrhosis_Liver_Year',50)->nullable();
		        $table->string('Kidney',50);
				$table->string('Kidney_Year',50)->nullable();
				$table->string('High_Blood_Pressure',50);
				$table->string('High_Blood_Pressure_Year',50)->nullable();
				$table->string('Cardiovascular',50);
		        $table->string('Cardiovascular_Year',50)->nullable();
				$table->string('Allergy',50);
				$table->string('Allergy_Year',50)->nullable();
				$table->string('Autoimmunity',50);
				$table->string('Autoimmunity_Year',50)->nullable();
		        $table->string('Arthritis',50);
				$table->string('Arthritis_Year',50)->nullable();
				$table->string('Cancer',50)->nullable();
				$table->string('Cancer_1',50);
				$table->string('Cancer_Year',50)->nullable();
				$table->string('Abdominal_Surgery',50);
		        $table->string('Abdominal_Surgery_Year',50)->nullable();
				$table->string('Stomach_Duodenal_Surgery',50);
				$table->string('Stomach_Duodenal_Surgery_Year',50)->nullable();
		        $table->string('Stomach_Duodenal_Surgery_1',50)->nullable();
				$table->string('Stomach_Duodenal_Surgery_2',50)->nullable();
				$table->string('Stomach_Duodenal_Surgery_3',50)->nullable();
		        $table->string('Stomach_Duodenal_Surgery_4',50)->nullable();
				$table->string('Stomach_Duodenal_Surgery_5',50)->nullable();
				$table->string('Stomach_Duodenal_Surgery_6',50)->nullable();
		        $table->string('Stomach_Milk_Tablets',50);
				$table->string('Stomach_Milk_Tablets_Year',50)->nullable();
				$table->string('Special_Ulcer_Treatment_Agent',50);
		        $table->string('Special_Ulcer_Treatment_Agent_Year',50)->nullable();
				$table->string('Joint_Medicine',50);
				$table->string('Joint_Medicine_Year',50)->nullable();
		        $table->string('Painkiller',50);
				$table->string('Painkiller_Year',50);
				$table->string('Blocking_Drugs',50);
				$table->string('Blocking_Drugs_Year',50)->nullable();
				$table->string('Asthma_Medicine',50);
		        $table->string('Asthma_Medicine_Year',50)->nullable();
				$table->string('Lowering_Uric_Acid',50);
				$table->string('Lowering_Uric_Acid_Year',50)->nullable();
				$table->string('Take_Probiotics',50);
		        $table->string('Take_Probiotics_Year')->nullable();
				$table->string('Unknown_Medicine',50);
				$table->string('Unknown_Medicine_Year',50)->nullable();
				$table->string('Woman_Pelvic_Cavity',50)->nullable();
		        $table->string('Woman_Pelvic_Cavity_2',50)->nullable();
				$table->string('Woman_Pelvic_Cavity_3',50)->nullable();
				$table->string('Woman_Vaginal',50)->nullable();
				$table->string('Woman_Vaginal_2',50)->nullable();
		        $table->string('Woman_Vaginal_3',50)->nullable();
				$table->string('Family_Chronic_Gastritis',50);
				$table->string('Family_Chronic_Gastritis_S',50)->nullable();
		        $table->string('Family_Gastric_Ulcer',50);
		        $table->string('Family_Gastric_Ulcer_S',50)->nullable();
				$table->string('Family_Duodenal_Ulcer',50);
				$table->string('Family_Duodenal_Ulcer_S',50)->nullable();
		        $table->string('Family_Gastric_Cancer',50);
		        $table->string('Family_Gastric_Cancer_S',50)->nullable();
				$table->string('Family_Other',50);
				$table->string('Family_Other_S',50)->nullable();
				$table->string('Family',50);
		        $table->string('Abdominal_Pain',50);
				$table->string('Abdominal_Discomfort',50);
				$table->string('Back_Pain',50);
		        $table->string('Bloating_Feeling',50);
				$table->string('Chest_Discomfort',50);
				$table->string('Overflow_Acid_Water',50);
				$table->string('Hiccups',50);
				$table->string('Poor_Taste',50);
				$table->string('Nausea',50);
		        $table->string('Vomit',50);
				$table->string('Dizziness',50);
				$table->string('Skin_Itch',50);
				$table->string('Black_Stool',50);
				$table->string('Constipation',50);
				$table->string('Soft_Stool',50);
		        $table->string('Number_of_Defecation',50);
		        $table->string('Detection_Helicobacter_Pylori',50);
				$table->string('Treatment_Helicobacter_Pylori',50);
				$table->string('Treatment_HP',50)->nullable();
		        $table->string('Recently_Taking_Antibiotics',50);
				$table->string('How_Taking_Antibiotics',50)->nullable();
		        $table->string('Before_Taking_Antibiotics',50);
				$table->string('Taking_Reason',50)->nullable();
				$table->string('Taking_Days',50)->nullable();
				$table->rememberToken();
            	$table->timestamps();           
        });*/
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //Schema::drop('patients');
    }
}
